config/routes.rb
Dungeonmaster::Application.routes.draw do
  devise_for :users

  resources :characters do
    resources :pets
  end

  resources :moves

  root to: "characters#index"
end

app/models/character.rb
class Character < ActiveRecord::Base
  attr_accessible :experience, :first_name, 
  :last_name, :hp, :level, :user, :character_class,
  :height, :weight, :strength, :luck, :intelligence,
  :sex_appeal, :gold

  validates :experience, :first_name, :last_name, 
    :hp, :level, :user, :character_class,
    :height, :weight, :strength, :luck, 
    :intelligence, :sex_appeal, :gold, {
      presence: true
    }

  validates :experience, :level, :hp, :height, 
    :weight, :strength, :luck, :intelligence, 
    :sex_appeal, :gold, {
      numericality: true
    }

  belongs_to :user
  belongs_to :character_class
  has_many :pets
  has_and_belongs_to_many :moves

  def charclass
    character_class.name
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def update_level
    if self.experience < 1000
      self.level = 1
    elsif self.experience >= 1000 && self.experience < 3000
      self.level = 2
    end
    self.save
  end
end

app/models/character_class.rb
class CharacterClass < ActiveRecord::Base
  attr_accessible :name

  validates :name, presence: true

  has_many :characters
  has_many :moves
end

app/models/character_moves.rb
class CharacterMoves < ActiveRecord::Base
  attr_accessible :character, :move

  validates :character, :move, {
    presence: true
  }

  belongs_to :character
  belongs_to :move
end

app/models/move.rb
class Move < ActiveRecord::Base
  attr_accessible :character_class, :description, :dice_type, :frequency, :number_of_dice, :range, :title

  validates :title, :frequency, :range, {
    presence: true
  }

  belongs_to :character_class
  has_and_belongs_to_many :characters
end

app/models/pet.rb
class Pet < ActiveRecord::Base
  attr_accessible :character, :first_name, :hp, 
  :last_name, :level, :experience, :strength, 
  :luck, :intelligence, :sex_appeal

  validates :first_name, :hp, 
    :character, :level, :experience,
    :strength, :luck, :intelligence,
    :sex_appeal, {
    presence: true
  }

  validates :hp, :level, :experience,
    :strength, :luck, :intelligence,
    :sex_appeal, {
    numericality: true
  }

  validates_uniqueness_of :first_name, 
    scope: :character_id, :message => "Character already has a pet by that name"

  belongs_to :character

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me, :username
  
  validates :email, :password, :username, {
    presence: true
  }

  validates_uniqueness_of :username, :email

  has_many :characters
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!

  def index
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_filter :authenticate_user!

  def new
    @character = current_user.characters.new
  end

  def create
    @class = CharacterClass.where(name: params[:character][:character_class].capitalize).first
    params[:character].delete(:character_class)
    @character = current_user.characters.new(params[:character])
    @character.character_class = @class

    if @character.save
      redirect_to @character
    else
      redirect_to new_character_path
    end
  end

  def show
    @character = Character.find(params[:id])
  end

  def index
    @characters = Character.all
  end

  def edit
    @character = Character.find(params[:id])
  end

  def update
    @character = Character.find(params[:id])
    @character.update_attributes(params[:character])
    @character.update_level

    redirect_to @character
  end

  def destroy
    @character = Character.find(params[:id])
    @character.delete
    @notice = "Character successfully banished from your clan."
    redirect_to characters_path
  end
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController
  def new
    @move = Move.new
  end

  def create
    @id = CharacterClass.where(name: params[:move][:character_class_id].capitalize).first.id
    params[:move].delete(:character_class_id)

    @move = Move.new(params[:move])
    @move.character_class_id = @id

    if @move.save
      redirect_to @move
    else
      redirect_to new_move_path
    end
  end

  def show
    @move = Move.find(params[:id])
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def new
    @errors = params[:errors] || nil
    @character = Character.find(params[:character_id])
    @pet = @character.pets.new
  end

  def create
    @character = Character.find(params[:pet][:character_id])
    params[:pet].delete(:character_id)
    @pet = @character.pets.new(params[:pet])

    if @pet.save
      redirect_to character_pet_path(@character, @pet)
    else
      @error = @pet.errors.messages
      redirect_to new_character_pet_path(@character, errors: @error)
    end
  end

  def show
    @character = Character.find(params[:character_id])
    @pet = Pet.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/index.html.erb
Hello, DungeonMaster!

app/views/characters/edit.html.erb
<div class="container">
  <div class="row">
    <div class="span12">
      <h1><%= @character.full_name %></h1>
      <%= form_for @character do |f| %>

        <%= f.label :first_name, "First Name" %>
        <%= f.text_field :first_name %>

        <%= f.label :last_name, "Last Name" %>
        <%= f.text_field :last_name %>

        <%= f.label :experience, "Experience" %>
        <%= f.text_field :experience %>

        <%= f.label :hp, "HP" %>
        <%= f.text_field :hp %>

        <%= f.label :gold, "Gold" %>
        <%= f.text_field :gold %>

        <%= f.label :height, "Height" %>
        <%= f.text_field :height %>

        <%= f.label :weight, "Weight" %>
        <%= f.text_field :weight %>

        <%= f.label :strength, "Strength" %>
        <%= f.text_field :strength %>

        <%= f.label :intelligence, "Intelligence" %>
        <%= f.text_field :intelligence %>

        <%= f.label :luck, "Luck" %>
        <%= f.text_field :luck %>

        <%= f.label :sex_appeal, "Sex Appeal" %>
        <%= f.text_field :sex_appeal %>

        <br><br>

        <%= f.submit "Edit Character", :class => "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/characters/index.html.erb
<div class="container">

  <h1>Characters</h1>

  <% if @notice %>
    <div class="row notice">
      <div class="span12">
        <p><%= @notice %></p>
      </div>
    </div>
  <% end %>

  <% unless @characters.empty? %>
    <div class="row">
      <div class="span12">
        <table class="table table-hover">
          <thead>
            <th>Name</th>
            <th>Class</th>
            <th>Level</th>
            <th>Experience</th>
            <th>Owner</th>
            <th>Actions</th>
          </thead>
          <tbody>
            <% @characters.each do |character| %>
              <tr>
                <td><%= link_to "#{character.full_name}", character_path(character) %></td>
                <td><%= character.charclass %></td>
                <td><%= character.level %></td>
                <td><%= character.experience %></td>
                <td><%= character.user.username %></td>
                <td><%= link_to "Edit", edit_character_path(character) %></td>
                <td><%= link_to "Banish", character_path(character), method: :delete %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  <% end %>

  <%= link_to "Create Character", new_character_path, :class => "btn btn-primary" %>

</div>

app/views/characters/new.html.erb
<div class="container">
  <div class="row">
    <div class="span12">
      <h1>New Character</h1>
      <%= form_for @character do |f| %>

        <div class="new-character-move-box">
            <%= f.label :moves, "Moves" %>
            <%= f.select :moves, Move.all %>
        </div>

        <%= f.label :first_name, "First Name" %>
        <%= f.text_field :first_name %>

        <%= f.label :last_name, "Last Name" %>
        <%= f.text_field :last_name %>

        <%= f.label :hp, "HP" %>
        <%= f.text_field :hp %>

        <%= f.label :gold, "Gold" %>
        <%= f.text_field :gold %>

        <%= f.label :character_class, "Class" %>
        <%= f.select :character_class, ["Wizard", "Monk", "Elf", "Dark Elf", "Troll", "Warrior", "Barbarian", "Mage", "Battle Mage", "Bard", "Goblin" ] %>

        <%= f.label :height, "Height" %>
        <%= f.text_field :height %>

        <%= f.label :weight, "Weight" %>
        <%= f.text_field :weight %>

        <%= f.label :strength, "Strength" %>
        <%= f.text_field :strength %>

        <%= f.label :intelligence, "Intelligence" %>
        <%= f.text_field :intelligence %>

        <%= f.label :luck, "Luck" %>
        <%= f.text_field :luck %>

        <%= f.label :sex_appeal, "Sex Appeal" %>
        <%= f.text_field :sex_appeal %>

        <br><br>

        <%= f.submit "Create Character", :class => "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/characters/show.html.erb
<div class="container">
  <div class="row">
    <div class="span12">

      <!-- Character Stats -->
      <h1><%= @character.full_name %></h1>
      <table class="table table-striped">
        <thead>
          <th>Class</th>
          <th>Level</th>
          <th>HP</th>
          <th>Experience</th>
          <th>Gold</th>
          <th>Height</th>
          <th>Weight</th>
          <th>Str.</th>
          <th>Int.</th>
          <th>Luck</th>
          <th>Sexy</th>
        </thead>
        <tbody>
          <tr>
          <td><%= @character.charclass %></td>
          <td><%= @character.level %></td>
          <td><%= @character.hp %></td>
          <td><%= @character.experience %></td>
          <td><%= @character.gold %></td>
          <td><%= @character.height %></td>
          <td><%= @character.weight %></td>
          <td><%= @character.strength %></td>
          <td><%= @character.intelligence %></td>
          <td><%= @character.luck %></td>
          <td><%= @character.sex_appeal %></td>
        </tbody>
      </table>
      <!-- End Character Stats -->

      <!-- Pets -->
      <% unless @character.pets.empty? %>
        <h1>Pets</h1>
        <table class="table table-striped">
          <thead>
            <th>Name</th>
            <th>HP</th>
          </thead>
          <tbody>
            <% @character.pets.each do |pet| %>
              <tr>
                <td><%= link_to "#{pet.full_name}", character_pet_path(@character, pet) %></td>
                <td><%= pet.hp %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
      <!-- End Pets -->

      <!-- Links -->
      <%= link_to "Edit #{@character.first_name}", edit_character_path(@character), :class => "btn btn-warning" %>
      <%= link_to "View All Characters", characters_path, :class => "btn btn-primary" %>
      <%= link_to "Create Pet for Character", new_character_pet_path(@character), :class => "btn btn-success" %>
      <!-- End Links -->
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DungeonMaster</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/moves/new.html.erb
<div class="container">
  <div class="row">
    <div class="span12">
      <h1>New Move</h1>
      <%= form_for @move do |f| %>

        <%= f.label :title, "Title" %>
        <%= f.text_field :title %>

        <%= f.label :description, "Description" %>
        <%= f.text_area :description %>

        <%= f.label :frequency, "Frequency" %>
        <%= f.select :frequency, ["At will", "Encounter", "Daily"]  %>

        <%= f.label :character_class_id, "Class" %>
        <%= f.select :character_class_id, ["Wizard", "Monk", "Elf", "Dark Elf", "Troll", "Warrior", "Barbarian", "Mage", "Battle Mage", "Bard", "Goblin" ] %>

        <%= f.label :number_of_dice, "Number of Dice" %>
        <%= f.select :number_of_dice, ["1", "2", "3", "4", "5", "6"] %>

        <%= f.label :dice_type, "Type of Die" %>d
        <%= f.select :dice_type, ["2", "4", "6", "8", "10", "12", "20"] %>

        <%= f.label :range, "Range (# of squares)" %>
        <%= f.text_field :range %>

        <br><br>

        <%= f.submit "Create Move", :class => "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/moves/show.html.erb
<div class="container">
  <div class="row">
    <div class="span12">

      <h1><%= @move.title %></h1>
      <table class="table table-striped">
        <thead>
          <th>Description</th>
          <th>Class</th>
          <th>Frequency</th>
          <th>Attack</th>
          <th>Range</th>
        </thead>
        <tbody>
          <tr>
          <td><%= @move.description %></td>
          <td><%= @move.character_class.name %></td>
          <td><%= @move.frequency %></td>
          <td><%= "#{@move.number_of_dice}d#{@move.dice_type}" %></td>
          <td><%= @move.range %></td>
        </tbody>
      </table>

      <!-- Links -->
      <%= link_to "View All Characters", characters_path, :class => "btn btn-primary" %>
      <%= link_to "Create Another Move", new_move_path, :class => "btn btn-success" %>
      <!-- End Links -->
    </div>
  </div>
</div>

app/views/pets/new.html.erb
<div class="container">
  <% if @errors %>
    <div class="row alert alert-error">
      <div class="span12 error">
        <% @errors.each do |error| %>
          <p><%= error[1][0] %></p>
        <% end %>
      </div>
    </div>
  <% end %>
  <div class="row">
    <div class="span12">
      <h1>New Pet for <%= @character.full_name %></h1>
      <%= form_for [@character, @pet] do |f| %>

        <%= f.label :first_name, "First Name" %>
        <%= f.text_field :first_name %>

        <%= f.label :last_name, "Last Name" %>
        <%= f.text_field :last_name %>

        <%= f.label :hp, "HP" %>
        <%= f.text_field :hp %>

        <%= f.label :strength, "Strength" %>
        <%= f.text_field :strength %>

        <%= f.label :luck, "Luck" %>
        <%= f.text_field :luck %>

        <%= f.label :intelligence, "Intelligence" %>
        <%= f.text_field :intelligence %>

        <%= f.label :sex_appeal, "Sex Appeal" %>
        <%= f.text_field :sex_appeal %>

        <%= f.hidden_field :character_id, :value => @character.id %>

        <br><br>

        <%= f.submit "Create Pet", :class => "btn btn-primary" %>

      <% end %>
    </div>
  </div>
</div>

app/views/pets/show.html.erb
<div class="container">
  <div class="row">
    <div class="span12">
      <h1><%= @pet.full_name %></h1>
      <p><%= @character.full_name %>'s pet</p>
      <table class="table table-striped">
        <thead>
          <th>HP</th>
          <th>Level</th>
          <th>Experience</th>
          <th>Str.</th>
          <th>Luck</th>
          <th>Int.</th>
          <th>Sexy</th>
        </thead>
        <tbody>
          <tr>
            <td><%= @pet.hp %></td>
            <td><%= @pet.level %></td>
            <td><%= @pet.experience %></td>
            <td><%= @pet.strength %></td>
            <td><%= @pet.luck %></td>
            <td><%= @pet.intelligence %></td>
            <td><%= @pet.sex_appeal %></td>
        </tbody>
      </table>
      <%= link_to "View All Characters", characters_path, :class => "btn btn-primary" %>
      <%= link_to "Return to #{@character.first_name}", character_path(@character), :class => "btn btn-primary" %>
    </div>
  </div>
</div>